### ISSUE TITLE
Text too small on e-reader

### ISSUE THREAD

**Issue by gdetrez** [hipstermojo/paperoni#19]
I recently installed paperoni 0.5.0 (from 0.4.1) and I suspect the new CSS is interacting with the epub rendering on my e-reader (remarkable 2) in a such a way that the text becomes so small it is barely readable anymore.  In addition, but that's a minor issue, the spacing around the titles has become a bit  extreme, at least to my taste.

Here's an example of the two first page of an article converted to epub by paperoni and rendered on the tablet. 

with 0.4.1:
<img width=40% src="https://user-images.githubusercontent.com/38019/125818185-196fe914-c59a-48d7-9b3e-768ef31d9c96.png" /><img width=40% src="https://user-images.githubusercontent.com/38019/125818177-d9be4d8f-667c-4f07-aa22-0f0a58a36147.png" />

with 0.5.0:
<img src="https://user-images.githubusercontent.com/38019/125818150-08033c7e-f527-4b17-bf47-67bcb34b4ea4.png" width=40% /> <img width=40% src="https://user-images.githubusercontent.com/38019/125818157-59369e0e-61a7-40e6-a8c1-3fda3c9dd9f5.png" />
</details>

My understanding is that consistent epub rendering is hard as every device/manufacturer/app does things differently (a bit like the web of two decades ago...)
Maybe paperoni could have an option to disable the custom CSS to work around issues like this?

**Comment by hipstermojo** [comment]
Hi @gdetrez. The font size issue might be easy to address if ReMarkable's ereader allows you to change the font sizes. It's hard to find CSS that will work generically across most articles. Nonetheless, I will add a flag to disable the CSS added to the epub.
I'll close this issue when the next PR is merged to master.

**Comment by hipstermojo** [comment]
Disabling the custom CSS entirely could lead to really bad layout of things like code blocks and images so I think I will instead add two separate flags:
- `no-header-css` which would mean that the typography (font sizes, margins, font family etc) is left to the e-reader to configure
- `no-css` which would completely remove all CSS from the output EPUB but also mean that large images and wide code blocks will overflow and affect pdf generation.

Would that be a favourable outcome?

Also, I can make a push to the dev branch with this fix before the end of the day for you to try if you have Rust installed, rather than have you wait until 24th (the monthly release date).

**Comment by gdetrez** [comment]
Hi!  Sorry for the delayed answer.

The available font sizes on the tablet are limited and even with the largest size the text is too small for me to read comfortably.

I don't really know how the reMakable will handle either solution but I do have rust installed so I should be able to test them easily if you make them on a dev branch.

An other option might be to add an option to pass a custom CSS.  That way one could customize the default CSS to their Reader and keep the nice things (image sizes, code blocks...) and remove only the undesirable parts.

**Comment by hipstermojo** [comment]
The option for custom CSS can also be added. The only issue would be validating the CSS file to ensure that it's valid CSS syntax. Validating the syntax isn't crucial to the Epub exports but it may cause certain strict Epub readers to fail to parse the Epub files.

**Comment by hipstermojo** [comment]
Hi @gdetrez . You can pull the latest commit on dev and try it now. 
But it doesn't have support for adding custom CSS just yet.

**Comment by hipstermojo** [comment]
I'd like to close this issue but feel free to reopen it if the issue about the CSS is still persistent after the changes.

**Comment by gdetrez** [comment]
@hipstermojo the `--no-css` option works for me.  It looks like it gives me the same result as the old version. 

Regarding validating custom CSS files, maybe you can use the cssparser crate for that? It seems that paperoni is already including this crate as a transitive dependency anyway.

**Comment by hipstermojo** [comment]
Thanks for the suggestion, I'll look into it when I work on the next release.
