### ISSUE TITLE
Possible to provide as (C/C++) library?

### ISSUE THREAD

**Issue by plata** [hipstermojo/paperoni#23]

**Comment by hipstermojo** [comment]
Hi @plata. Unfortunately, the way Paperoni is currently organized, it can't be exported even as a Rust library crate. But I have plans to make some parts available as libraries.
I also haven't worked with the parts of allowing for FFI bindings so that it can be called from C/C++ or any other language for that matter.
Which parts had you wanted to access as a library?

**Comment by plata** [comment]
My use case would be to call paperoni with the URL (or HTML + URL) and get back the "cleaned" HTML.

So something like: `std::string paperoni(const std::string& url)`

**Comment by hipstermojo** [comment]
Alright. Well that could be doable without needing to make FFI bindings.
You could instead call paperoni in a shell in C/C++ (I don't know the exact term used to refer to shelling out in C/C++) and then read the value returned from `stdout` back into a `string` in your C/C++. This assumes that you want to use paperoni in a context that permits shelling out.

NOTE: Getting content from `stdout` isn't actually supported yet so this is just a hypothetical solution.

Would that work for you?

**Comment by plata** [comment]
I fear it won't work. It shall also work on Android and my current knowledge is that starting a subprocess there is an issue. However, my Android knowledge is limited so this might be wrong.

**Comment by hipstermojo** [comment]
If it's going to be on Android then it certainly won't work with that approach.
If all you needed was to pass in some HTML and get back some HTML containing only the article, then you only need the `readability` portion of paperoni which is actually based on the Mozilla library. There's many existing ports to other languages, for example in Android you can use Kotlin libs like [Readabilty4J](https://github.com/dankito/Readability4J) and [crux](https://github.com/chimbori/crux). I've not tried them but they seem to do just the same thing.

There's also this [arc90 readability](https://github.com/masukomi/arc90-readability) C++ port which isn't exactly the same as the Mozilla one but should be sufficient for your needs.

**Comment by plata** [comment]
I'm aware about the Kotlin implementations and yes, I could probably use that as a service on Android. However, I would prefer a solution which works for Linux/Windows as well.

Which C++ port are you referring to? rdrview? I've tried that, it's only an executable.

Don't get me wrong, I'm not asking you to solve my problems. Feel free to close the issue if paperoni as library doesn't fit into your plans.

**Comment by hipstermojo** [comment]
Making the readability portion of paperoni an independent library is definitely something I had planned for but having FFI bindings for C/C++ is definitely out of its scope. I hope you get a solution for your needs though.
If and when I do make it a library crate, I might reopen this issue but don't hold your breath for that.
