### ISSUE TITLE
Project still maintained/developed?

### ISSUE THREAD

**Issue by kemitix** [hipstermojo/paperoni#25]
Hi, Is this project still being developed or maintained. I see from your comment in #22 that you had intended to do a release in late Jan 2022. You appear not have have made any changes since.

I had been thinking about developing just this sort of tool in Rust before I found `paperoni`, and would be happy to work with you on it, or if you are no longer interested in the project, to adopt it.

**Comment by hipstermojo** [comment]
Hi @kemitix. Thank you for showing interest in it!
I haven't had much time to work on any features or releases for paperoni so it might as well be considered to be archived for now. I would recommend forking it if you're looking to get any new things out for it, it's MIT licensed so you can do as you wish (within reason).
One caveat to keep in mind is that the HTML library used to parse the html content: [kuchiki](https://github.com/kuchiki-rs/kuchiki) is archived so any changes to those parts may not be as trivial.

**Comment by kemitix** [comment]
Thanks for the reply. I've done some updates to dependencies, and replacing kuchiki would be the next task.

**Comment by kemitix** [comment]
The work I've been doing is here: https://git.kemitix.net/kemitix/paperoni
