### ISSUE TITLE
Option to add multiple URLs as chapters

### ISSUE THREAD

**Issue by gdetrez** [hipstermojo/paperoni#9]
Hi! I've been using paperoni for a few weeks to load web articles on my e-reader, and I'm very grateful that you made this and gave it to the world! :pray:

One feature I'm missing is the ability to have multiple URLs bundled together as a single epub file.  E.g. for multi-part blog articles or actual books that are published on the web with a URL per chapter.

Do you think it could be interesting to add this to paperoni?

I've done a bit of Rust, so if you're interested but don't have time to implement it, I might be able to contribute with some guidance to navigate the code :compass:

**Comment by hipstermojo** [comment]
Hi @gdetrez. Thank you for the feedback!
Paperoni currently supports this through the `merge` flag that was added in version [0.3.0-alpha1](https://github.com/hipstermojo/paperoni/releases/tag/v0.3.0-alpha1) I actually use it a lot when getting articles from my newsletters. The `merge` flag takes a string that will be the name of your output file.
So for example I can use it  like this:
```
paperoni https://example.com/index.html https://example.com/foo.html --merge "Example epub file.epub"
```

If you have your links in a file then you can just call it like this:
```
paperoni -f links.txt --merge "Example epub file.epub"
```

Please let me know if that addresses your needs :smile:

**Comment by gdetrez** [comment]
Hi @hipstermojo.  Thanks, that's exactly what I needed! It looks I missed the 0.3.0 release.

**Comment by hipstermojo** [comment]
Hope you enjoy the feature and be sure to look out for a new release on the last week of April :smile: !
